CREATE SCHEMA IF NOT EXISTS users;
CREATE TABLE IF NOT EXISTS users.users (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  balance NUMERIC(18,2) NOT NULL DEFAULT 0
);
GRANT USAGE ON SCHEMA users TO app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA users TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA users TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT USAGE, SELECT ON SEQUENCES TO app;

INSERT INTO users.users(name,balance)
SELECT name,balance FROM public.users
ON CONFLICT (name) DO NOTHING;

CREATE SCHEMA IF NOT EXISTS products;
CREATE TABLE IF NOT EXISTS products.symbols (
  symbol TEXT PRIMARY KEY,
  lot_size NUMERIC(18,6) NOT NULL DEFAULT 1
);
GRANT USAGE ON SCHEMA products TO app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA products TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA products GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO app;

CREATE SCHEMA IF NOT EXISTS orders;
CREATE TABLE IF NOT EXISTS public.positions (
  user_id INT REFERENCES users.users(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  qty NUMERIC(18,6) NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, symbol)
);

CREATE TABLE IF NOT EXISTS public.orders (
  id BIGSERIAL PRIMARY KEY,
  user_id INT REFERENCES users.users(id),
  side TEXT CHECK (side IN ('BUY','SELL')),
  symbol TEXT NOT NULL,
  price NUMERIC(18,6) NOT NULL,
  qty NUMERIC(18,6) NOT NULL,
  status TEXT NOT NULL DEFAULT 'NEW',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_orders_active
  ON public.orders (symbol, side, price, created_at) WHERE status='NEW';


GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO app;


INSERT INTO products.symbols(symbol, lot_size) VALUES ('AAPL',1) ON CONFLICT DO NOTHING;
