version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
      app3:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app1:
    build: ./app
    environment:
      - PORT=5001
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  app2:
    build: ./app
    environment:
      - PORT=5002
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  app3:
    build: ./app
    environment:
      - PORT=5003
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    ports:
      - "5003:5003"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
