# локальный доступ
local   all             all                                     trust
host    all             all             0.0.0.0/0               md5

# репликация
host    replication     repl            0.0.0.0/0               md5
