worker_processes auto;
events { worker_connections 1024; }

http {
  log_format short '$remote_addr - $request $status $upstream_addr $upstream_status $request_time cache:$upstream_cache_status';
  access_log /var/log/nginx/access.log short;

  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=apicache:10m max_size=100m inactive=1m use_temp_path=off;
  map $http_cache_bypass $bypass { default 0; "1" 1; }

  upstream backend_upstream  { server backend:8003; }
  upstream products_upstream { server products-service:8002; }
  upstream users_v1          { server users-service:8001; }
  upstream users_v2_try { server users-service-v2:8001 max_fails=1 fail_timeout=2s; server users-service:8001 backup;}


  map $arg_seed $canary_seed {
    "~.+"   $arg_seed;
    default "${remote_addr}${request_method}${uri}";
  }


  split_clients "$canary_seed" $canary {
    10%    v2;
    *      v1;
  }

  map $canary $users_upstream {
    v2       users_v2_try;
    default  users_v1;
  }


  server {
    listen 80;

    location = /healthz { return 200 "ok\n"; }

    location /api/users/ {
      rewrite ^/api/users/?(.*)$ /$1 break;
      proxy_pass http://$users_upstream;
      proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      proxy_next_upstream_tries 2;
      add_header X-Canary $canary always;
      add_header X-Service-Route $users_upstream always;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_no_cache 1;
      proxy_cache_bypass 1;
      proxy_set_header Connection close;
    }

    location /api/products/ {
      proxy_pass http://products_upstream/;
      proxy_no_cache 1; proxy_cache_bypass 1; add_header X-Cache-Status off;
      proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Connection close;
    }

    location /api/orders/ {
      proxy_pass http://backend_upstream/;
      proxy_no_cache 1; proxy_cache_bypass 1; add_header X-Cache-Status off;
      proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Connection close;
    }

    location = /api/time {
      rewrite ^/api/?(.*)$ /$1 break;
      proxy_pass http://backend_upstream;
      proxy_cache apicache; proxy_cache_methods GET HEAD; proxy_cache_valid 200 5s; proxy_cache_bypass $bypass;
      add_header X-Cache-Status $upstream_cache_status;
      add_header X-Geo "zone-2" always;
      proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header Connection close;
    }

  location = /api/whoami {
    proxy_pass http://backend_upstream/time;
    add_header X-Canary $canary always;
    add_header X-Service-Route $users_upstream always;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_no_cache 1;
    proxy_cache_bypass 1;
    proxy_set_header Connection close;
  }

    location /stub_status {
      stub_status;
      allow 127.0.0.1;
      allow 172.16.0.0/12;
      deny all;
    }
  }
}
